await txt2nft(
    "proof of space and time",
    2,
    "txch132deptk7d9x0wd70f92ttmrhznwht02xtyrsxzaz9suqkh0zx2jqah4syt",
    "this NFT was generated by stable-diffusion",
    "an ode to gpu miners",
    'A special NFT for former GPU miners'
)
